
spring:
  datasource:
    url: jdbc:postgresql://dpg-d0qq1kre5dus739q1eq0-a.oregon-postgres.render.com:5432/delivery_bd?sslmode=require
    username: delivery_bd_user
    password: 4OeHUn5DK2JKCNtupxCmEO8epqBNSeF6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    com.example.delivery: DEBUG
