spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://dpg-d0qq1kre5dus739q1eq0-a.oregon-postgres.render.com:5432/delivery_bd?sslmode=require
    username: delivery_bd_user
    password: 4OeHUn5DK2JKCNtupxCmEO8epqBNSeF6
    driver-class-name: org.postgresql.Driver

  # JPA + Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  # Liquibase
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  # Ініціалізація test-даних із data.sql
  sql:
    init:
      mode: always                # запускати data.sql завжди
      data-locations: classpath:data.sql

  # OAuth2 (Google)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1070494132784-ef1gi3g9t8i23t3ub9aqeo1moequrf6e.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [openid, profile, email]
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri:          https://oauth2.googleapis.com/token
            user-info-uri:      https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    com.example.delivery: DEBUG
